---
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function resource stack creation
Resources:
  LambdaFunctionOne:
    Type: AWS::Lambda::Function
    Properties:
      # CodeUri: s3://smartphotofrontend/lf1.zip
      Code:
        S3Bucket: smartphotofrontend
        S3Key: lf1.zip
      Handler: index-photos.lambda_handler
      FunctionName: index-photos
      Role: 'arn:aws:iam::493645893741:role/service-role/index-photos-role-f9lode4s'
      Runtime: Python3.9
    DeletionPolicy: Retain
  LambdaFunctionTwo:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: smartphotofrontend
        S3Key: lf2.zip
      # CodeUri: s3://smartphotofrontend/lf2.zip
      Handler: lambda_function.lambda_handler
      FunctionName: search-photos
      Role: 'arn:aws:iam::493645893741:role/service-role/search-photos-role-cd73n5tm'
      Runtime: Python3.9
    DeletionPolicy: Retain
Outputs:
  FunctionOneName:
    Value:
      Ref: LambdaFunctionOne
  FunctionTwoName:
    Value:
      Ref: LambdaFunctionTwo
  # LambdaExecutionRole:
  #   Type: AWS::IAM::Role
  #   Properties:
  #     RoleName:
  #     AssumeRolePolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #       - Effect: Allow
  #         Principal:
  #           Service:
  #           - lambda.amazonaws.com
  #         Action:
  #         - sts:AssumeRole
  # lambdaexecutionpolicy:
  #   DependsOn:
  #   - LambdaExecutionRole
  #   Type: AWS::IAM::Policy
  #   Properties:
  #     PolicyName: lambda-execution-policy
  #     Roles:
  #     - Ref: LambdaExecutionRole
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #       - Effect: Allow
  #         Action:
  #         - logs:CreateLogGroup
  #         - logs:CreateLogStream
  #         - logs:PutLogEvents
  #         Resource:
  #         - Fn::Sub:
  #           - arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
  #           - region:
  #               Ref: AWS::Region
  #             account:
  #               Ref: AWS::AccountId
  #             lambda:
  #               Ref: LambdaFunction
  #         - Fn::Sub:
  #           - arn:aws:logs:${region}:${account}:log-group:/aws/lambda/${lambda}:log-stream:*
  #           - region:
  #               Ref: AWS::Region
  #             account:
  #               Ref: AWS::AccountId
  #             lambda:
  #               Ref: LambdaFunctionTwo
# Outputs:
#   FunctionOneName:
#     Value:
#       Ref: LambdaFunction
#   FunctionOneArn:
#     Value:
#       Fn::GetAtt:
#       - LambdaFunction
#       - Arn
#   FunctionTwoName:
#     Value:
#       Ref: LambdaFunctionTwo
#   FunctionTwoArn:
#     Value:
#       Fn::GetAtt:
#       - LambdaFunctionTwo
#       - Arn
#   Region:
#     Value:
#       Ref: AWS::Region
#   LambdaExecutionRole:
#     Value:
#       Ref: LambdaExecutionRole